language: php

php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

matrix:
  allow_failures:
    - php: "7.1"
      env: DOKUWIKI=old-stable
    - php: "hhvm"

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
  - DOKUWIKI=old-stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh

script:
  - cd _test && PRESERVE_TMP=false phpunit --stderr --group plugin_webmaster --verbose --debug
