dist: trusty
language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  - "hhvm"

matrix:
  allow_failures:
    - php: "hhvm"

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh

script:
  - cd _test && PRESERVE_TMP=false phpunit --stderr --group plugin_webmaster --verbose --debug
